
services:
  db:
    image: postgres:14
    container_name: pandavideo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pandavideo
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: pandavideo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./back-end
    container_name: pandavideo-backend
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ./back-end:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/pandavideo
      REDIS_URL: redis://redis:6379
      PANDAVIDEO_API_URL: https://api-v2.pandavideo.com.br
      PANDAVIDEO_API_KEY: seu_api_token_aqui
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./front-end
    container_name: pandavideo-frontend
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ./front-end:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev"]
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend

volumes:
  db_data:
  backend_node_modules: